openapi: "3.0.0"
servers:
  - description: Demo API
    url: https://demo-api.herokuapp.com/api/
info:
  description: This API represents the core Demo API. See info on verbs here https://restfulapi.net/http-methods/

  version: "2.0"
  title: Demo API
  contact:
    email: heedris2olubisi@gmail.com
  license:
    name: Proprietary
    url: "https://demo-api.herokuapp.com/api/"

##################################################
##### Tags in the system

tags:
  - name: City
    description: Endpoint for managing cities in the system
    externalDocs:
      url: https://demo-api.herokuapp.com/api/

paths:
  #####################################
  ### City
  /cities:
    get:
      tags:
        - City
      summary: Return all cities

      responses:
        "200":
          description: All cities
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/City"

components:
  schemas:
    # Information provided when all cities is retrieved successfully
    City:
      type: object
      properties:
        name:
          type: string
        name_native:
          type: string
        country:
          type: string
        continent:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        population:
          type: number
        founded:
          type: number
        landmarks:
          type: array
          items:
            type: string

externalDocs:
  url: https://demo-api.herokuapp.com/api/
  description: Official Documentation
